---

- name: Increase vm.max_map_countt
  shell: sysctl -w vm.max_map_count=262144

- name: Add docker GPG key
  apt_key:
    url: "{{ ansible_docker_repo_key }} "
    id: "{{ ansible_docker_repo_key_id }}"

- name: Add docker Repository
  apt_repository:
    repo: "{{ ansible_docker_repo }}"


- name: install Docker and dependencies
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  with_items: "{{ packages}}"

- name: Add  user to docker group
  user:
    name: "{{ ansible_user }}"
    group: "{{ docker_group }}"

- name: Create docker service directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  notify: 
    - restart docker

- name: Ensure Docker is runnig 
  service:
    name: docker
    state: started
    enabled: yes
